openapi: 3.0.3
info:
  description: This backend service used to <bold>Draft / Schedule</bold> to Auto
    send and send instant emails.
  title: Mail Scheduler
  version: 1.0.0
servers:
- description: Local server
  url: http://localhost:8000/api
paths:
  /create-job:
    post:
      description: Create a new job
      operationId: createJob
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Draft Job created successfully and response body is returned
            as follows.
      summary: Create a new job
      tags:
      - jobs
      x-accepts: application/json
components:
  schemas:
    inline_response_200:
      example:
        status_code: 0
        created_at: 2022-09-22T08:15:20.45609Z
        id: 6
        draft_id: draft_id
        status: "0"
      properties:
        status_code:
          description: Status code of the response wrapped in response body.
          type: integer
        id:
          description: Draft Primary id
          type: integer
        draft_id:
          description: Draft id
          type: string
        status:
          description: Draft status
          enum:
          - "0"
          - "1"
          - "2"
          type: string
        created_at:
          description: Draft created at
          example: 2022-09-22T08:15:20.45609Z
          format: date-time
          type: string
      type: object

